### ISSUE TITLE
Add Italy COVID-19 layers to demo

### ISSUE THREAD

**Issue by francbartoli** [geopython/demo.pygeoapi.io#13]
In https://demo.pygeoapi.io/covid-19 global COVID-19 is shown as directly proxied from official sources like the JHU.

Via this issue cases/layers are added specific for the Italy.

**Comment by francbartoli** [comment]
In https://demo.pygeoapi.io/covid-19 global COVID-19 is shown as directly proxied from official sources like the JHU.

Via this issue cases/layers are added specific for the Italy.

**Comment by tomkralidis** [comment]
@francbartoli I think this can be closed?
