### ISSUE TITLE
add a basic stac configuration to the demo instance 

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/demo.pygeoapi.io#20]
it is usefull to have a small configuration of a stac dataset to demonstrate the wide range of usecases supported by pygeoapi, also usefull for developers te develop and/or check complience of/to stac clients

**Comment by tomkralidis** [comment]
Added simple STAC setup in 739c9b2132d318fd7834ee3ed9afc6705889beb4

https://demo.pygeoapi.io/master/stac

@pvgenuchten please close if this works for you.
