### ISSUE TITLE
add a OACov demo 

### ISSUE THREAD

**Issue by jorgejesus** [geopython/demo.pygeoapi.io#21]
Prepare demo with data for OACOV using rasterio/xarray. Example conf and data

@tomkralidis  Maybe I can prepare some dataset from [soilgrids project](https://soilgrids.org)

**Comment by tomkralidis** [comment]
@jorgejesus do you have any GeoTIFF or CF compliant NetCDF data we can use?

**Comment by tomkralidis** [comment]
Added GRIB2 data setup in 739c9b2132d318fd7834ee3ed9afc6705889beb4

https://demo.pygeoapi.io/master/collections/gdps-temperature

Closing for now.  @jorgejesus if you can provide some SoilGrids data I can help set that up as another OACov collection.
