### ISSUE TITLE
add OATiles demo

### ISSUE THREAD

**Issue by tomkralidis** [geopython/demo.pygeoapi.io#29]
As discussed at the [May 2021 OGC API Virtual Code Sprint](https://github.com/opengeospatial/ogcapi-code-sprint-2021-05), add OATiles example.  cc @francbartoli

**Comment by tomkralidis** [comment]
@justb4 there's an fix needed in the MVT provider (see https://github.com/geopython/pygeoapi/issues/695), hence closing of #31

**Comment by justb4** [comment]
@tomkralidis ok clear, maybe I can assist later this afternoon.

**Comment by tomkralidis** [comment]
Thanks @justb4, implemented by @francbartoli and merged into master branch.  Let's see when demo pulls in the update to test.

**Comment by tomkralidis** [comment]
Looks like it works now: https://demo.pygeoapi.io/master/collections/lakes/tiles?f=html

Thanks @francbartoli and @justb4 !

**Comment by justb4** [comment]
Yes, seeing vector tiles for the lakes! 
https://demo.pygeoapi.io/master/collections/lakes/tiles thanks @francbartoli and @tomkralidis !
