### ISSUE TITLE
add raw sources of Dutch metadata

### ISSUE THREAD

**Issue by tomkralidis** [geopython/demo.pygeoapi.io#34]
As discussed at the [OGC Virtual Sprint](https://github.com/opengeospatial/ogcapi-code-sprint-2021-07), we should have the raw XML sources of the Dutch metadata collection in https://github.com/geopython/demo.pygeoapi.io/tree/master/services/pygeoapi_master/data/nationaalgeoregister.nl, along with possibly a `README.md` with an overview/link to authoritative source(s).

**Comment by tomkralidis** [comment]
@pvgenuchten any update on this one?  We need to regenerate the TinyDB repository given new changes in OARec.

**Comment by pvgenuchten** [comment]
Tom, does this help? or it needs some processing?
[md.zip](https://github.com/geopython/demo.pygeoapi.io/files/8860924/md.zip)

**Comment by tomkralidis** [comment]
Thanks @pvgenuchten.  Added in https://github.com/geopython/demo.pygeoapi.io/tree/master/services/pygeoapi_master/data/nationaalgeoregister.nl
